version: '3'
services:
  app:
    container_name: darthnest
    image: darthven/darthnest
    restart: always
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - '3000:3000'
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - mongodb:/data/db
    ports:
      - '27018:27017'
volumes:
  mongodb:
networks:
  default:
    driver: bridge
