FROM node:16.17.0
ENV NODE_ENV=production
WORKDIR /app
COPY ["package.json", "yarn.lock", "tsconfig.build.json", "./"]
RUN yarn global add @nestjs/cli
RUN yarn install
RUN yarn build
COPY dist .
CMD ["yarn", "start"]
